* What's this project
It's a set of scripts that downloads my playlists.

* How does it work?
** Playlists

This is how I associate youtube's playlist ID's to easily rememberable playlist file names.
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  playlists=(
      PLEITERw4PaKFs_uS0MoXkIfGbsYJHmWVU:balatro.m3u
      PLY9u9wC7ApRJk-tG4_pBtH6ubEJ7svnOB:celeste.m3u
      PLmOldskd2VbL7_t-NE9p6rEboq_v0AHko:hollow_knight.m3u
      PLbJE2f8Bl_gRq7g69Z4xfHV7Je-WWvpdJ:terraria.m3u
      PLsuCmTriuYXdOYZVaKyex5lIy3lT9K_PW:calamity.m3u
      PLfA6eOuWprRO33noGigJRXO1WXbkfmIlV:calamity_infernum.m3u
      PLMoZgWjm14OF2AWFfPc3cyQH7T2SC89jo:baba.m3u
      PLEUKcNuP7bDX9RoW3HqYR6EFvWZh12upZ:deltarune.m3u
      PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg:undertale.m3u
      PLhPp-QAUKF_iiixYtOGmynw-BMEju-EWo:isaac_rebirth.m3u
      PLhPp-QAUKF_gJ9eB-wSlfliMT_6ymDuiI:isaac_afterbirth.m3u
      PL_sXFbaP261h0WAWyJWKHbLa_haABQHBt:isaac_repentance.m3u
      PLrWR7klg98H0DbavfBz66OJO_E3wxKVSZ:isaac_antibirth.m3u
      PLNG8gFz9vUpsLXnWdCEf0svaFEfbY-kHh:minecraft.m3u
      PLyfXx1BeqwFbl5jg6swxk1XonI-4ldG9X:stardew_valley.m3u
      PLKDOdCjxOjzL6dnS9DsU4aNYU0ignNtWD:cassette_beasts.m3u
      PLTsWV3v1dCwpsDgjj2MLiBugQGH_H8D09:RoA.m3u
      PLHVUN_wezMf9LHGahDuuIiPlog4LI9J8k:rhythm_doctor.m3u
  )
#+end_src

** Generating the playlist files concurrently

This is pretty gnarly by my standards.
Basically, you make an array to sequence commands by looping once and then running the long running tasks in parallel by launching multiple subshells and using '&'.

It's important that this runs in a subshell or else ctrl-c wouldn't kill all the processes.
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  commands=()

  mkdir playlists

  for playlist_item in ${playlists[@]}; do
      commands+=("echo \"Generating $(echo ${playlist_item##*:})\" & yt-dlp --restrict-filenames -o '../pool/%(title)s.opus' --get-filename \" \$(echo ${playlist_item##:*})\" > \"$(echo playlists/${playlist_item##*:})\" &")
  done

  (trap 'kill 0' SIGINT; eval ${commands[*]} wait)
#+end_src

** Generating custom playlists

This simply generates the everything playlist which represents all the songs.

More playlists coming soon...
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  cat playlists/celeste.m3u playlists/hollow_knight.m3u playlists/terraria.m3u playlists/calamity_infernum.m3u playlists/baba.m3u playlists/deltarune.m3u playlists/undertale.m3u playlists/isaac_rebirth.m3u playlists/isaac_afterbirth.m3u playlists/isaac_repentance.m3u playlists/isaac_antibirth.m3u playlists/minecraft.m3u playlists/stardew_valley.m3u playlists/cassette_beasts.m3u playlists/RoA.m3u playlists/rhythm_doctor.m3u > playlists/everything.m3u
#+end_src

** Slowing down balatro tracks

I wanted to sequence this, however, I couldn't get this to work for whatever reason, it seemed to hang. It's only 5 tracks though, so it's not really a big issue.

Tracks are slowed down to 75% of of their original speed, just like in the game.
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  handle_balatro () {
      mkdir -p "pool/tmp"
      cd "pool/tmp"
      echo "$(echo ${1##:*})"
      yt-dlp -x --audio-quality 0 --audio-format opus --restrict-filenames -o '%(title)s' "$(echo ${1##:*})";
      balatro_list="$(ls -1)"
      for track in $balatro_list; do
	  echo "track: ($track)"
	  ffmpeg -y -i "$track" -strict -2 -filter:a "atempo=0.75" -vn "../$track" &
      done

      cd "../.."
      rm "pool/tmp" -r
  }
#+end_src

** Downloading all the playlist songs in parallel

Again, I sequence operations, then run them all at once.
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  commands=()

  for playlist_item in ${playlists[@]}; do
      if [ "balatro.m3u" = "$(echo ${playlist_item##*:})" ]; then
	  commands+=("echo \"\" & handle_balatro \"$playlist_item\" &")
      else
	  commands+=("echo \"Downloading: $(echo ${playlist_item##:*})\" & yt-dlp -x --audio-quality 0 --audio-format opus --restrict-filenames -o 'pool/%(title)s' \"$(echo ${playlist_item##:*})\" &")
      fi
  done;

  (trap 'kill 0' SIGINT; eval ${commands[*]} wait)
#+end_src
* Generate a specific playlist
  _Run this in the toplevel directory_
  _Don't download anything in the 'balatro.m3u' playlist unless you want to hear it sped up._
  #+begin_src shell
  yt-dlp --restrict-filenames -o 'pool/%(title)s.opus' --get-filename '<playlist-id>' > '<playlist-name>' && notify-send "Finished generating playlist"
  #+end_src
* Download a song
  _Run this in the pool directory_
  #+begin_src shell
    yt-dlp -x --audio-quality 0 --restrict-filenames -o '%(title)s' '<playlist-id>' && notify-send "Download Finished"
  #+end_src
* Playlists
** Celeste
   - id: =PLY9u9wC7ApRJk-tG4_pBtH6ubEJ7svnOB=
   - name: =celeste.m3u=
** Hollow Knight
   - id: =PLmOldskd2VbL7_t-NE9p6rEboq_v0AHko=
   - name: =hollow_knight.m3u=
** Terraria
   - id: =PLbJE2f8Bl_gRq7g69Z4xfHV7Je-WWvpdJ=
   - name: =terraria.m3u=
** Calamity
   - id: =PLsuCmTriuYXdOYZVaKyex5lIy3lT9K_PW=
   - name: =calamity.m3u=
** Calamity infernum
   - id: =PLfA6eOuWprRO33noGigJRXO1WXbkfmIlV=
   - name: =calamity_infernum.m3u=
** Baba
   - id: =PLMoZgWjm14OF2AWFfPc3cyQH7T2SC89jo=
   - name: =baba.m3u=
** Deltarune
   - id: =PLEUKcNuP7bDX9RoW3HqYR6EFvWZh12upZ=
   - name: =deltarune.m3u=
** Undertale
   - id: =PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg=
   - name: =undertale.m3u=
** Isaac Rebirth
   - id: =PLhPp-QAUKF_iiixYtOGmynw-BMEju-EWo=
   - name: =isaac_rebirth.m3u=
** Isaac Afterbirth
   - id: =PLyfXx1BeqwFa91omolDHEBUUC2Ip8f0l_=
   - name: =isaac_afterbirth.m3u=
** Isaac Repentance
   - id: =PL_sXFbaP261ituF7mOuSGHhfmn9G6GIwf=
   - name: =isaac_repentance.m3u=
** Isaac Antibirth
   - id: =PLrWR7klg98H0DbavfBz66OJO_E3wxKVSZ=
   - name: =isaac_antibirth.m3u=
** Minecraft
   - id: =PLefKpFQ8Pvy5aCLAGHD8Zmzsdljos-t2l=
   - name: =minecraft.m3u=
** Stardew Valley
   - id: =PLoku_1Va0MjwRzYb1yfBS3Ob5eyKbBi2p=
   - name: =stardew_valley.m3u=
** Cassette beasts
   - id: =PLKDOdCjxOjzL6dnS9DsU4aNYU0ignNtWD=
   - name: =cassette_beasts.m3u=
** Rivals of aether
   - id: =PLCPLpSD-PMt7l7ZYcdLgBVH7VqmL-VC07=
   - name: =RoA.m3u=
** Rhythm doctor
   - id: =PLHVUN_wezMf9LHGahDuuIiPlog4LI9J8k=
   - name: =rhythm_doctor.m3u=
* All Playlist IDs
  #+begin_src shell
    playlists="PLY9u9wC7ApRJk-tG4_pBtH6ubEJ7svnOB PLmOldskd2VbL7_t-NE9p6rEboq_v0AHko PLbJE2f8Bl_gRq7g69Z4xfHV7Je-WWvpdJ PLsuCmTriuYXdOYZVaKyex5lIy3lT9K_PW PLfA6eOuWprRO33noGigJRXO1WXbkfmIlV PLMoZgWjm14OF2AWFfPc3cyQH7T2SC89jo PLEUKcNuP7bDX9RoW3HqYR6EFvWZh12upZ PLpJl5XaLHtLX-pDk4kctGxtF4nq6BIyjg PLhPp-QAUKF_iiixYtOGmynw-BMEju-EWo PLyfXx1BeqwFa91omolDHEBUUC2Ip8f0l_ PL_sXFbaP261ituF7mOuSGHhfmn9G6GIwf PLrWR7klg98H0DbavfBz66OJO_E3wxKVSZ PLefKpFQ8Pvy5aCLAGHD8Zmzsdljos-t2l PLoku_1Va0MjwRzYb1yfBS3Ob5eyKbBi2p PLKDOdCjxOjzL6dnS9DsU4aNYU0ignNtWD PLCPLpSD-PMt7l7ZYcdLgBVH7VqmL-VC07 PLHVUN_wezMf9LHGahDuuIiPlog4LI9J8k"
  #+end_src
* All Playlist names
  #+begin_src shell
    names="celeste.m3u hollow_knight.m3u terraria.m3u calamity.m3u calamity_infernum.m3u baba.m3u deltarune.m3u undertale.m3u isaac_rebirth.m3u isaac_afterbirth.m3u isaac_repentance.m3u isaac_antibirth.m3u minecraft.m3u stardew_valley.m3u cassette_beasts.m3u RoA.m3u rhythm_doctor.m3u"
  #+end_src
* Goals [12/15]
  - [ ] Tailored playlist
  - [X] Terraria
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Calamity Mod (Including extra)
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Calamity Infernum Mod
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Baba
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Deltarune
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Undertale
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Isaac [4/4]
    - [X] Issac Rebirth
      - [X] ID acquired
      - [X] Playlist generated
    - [X] Isaac Afterbirth
      - [X] ID acquired
      - [X] Playlist generated
    - [X] Isaac Repentance
      - [X] ID acquired
      - [X] Playlist generated
    - [X] Isaac Antibirth
      - [X] ID acquired
      - [X] Playlist generated
  - [X] Minecraft
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Stardew Valley
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Cassette beasts
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Rivals of aether
    - [X] ID acquired
    - [X] Playlist generated
  - [X] Rhythm doctor
    - [X] ID acquired
    - [X] Playlist generated
  - [ ] Drawn to life: The next chapter
    - [ ] ID acquired
    - [ ] Playlist generated
  - [ ] TF2
    - [ ] ID acquired
    - [ ] Playlist generated
* Random Playlist [0/1]
** making it
  - [ ] Make a youtube playlist with random stuff
    - [ ] ID acquired
    - [ ] Platlist generated
** Playlist items
  - [ ] Naz - Tay K Returns to Dreamland 4
  - [ ] Pink Clouds and sticky rain (lookup xidnaf)
  - [ ] smash bros brawl main theme
  - [ ] smash bros ultimate main theme
  - [ ] Xomu - Walpurgis Night
  - [ ] Terraria Slimeium Mod OST - Gelatinous Grasslands
