#+TITLE: The Playlist
#+AUTHOR: FFFluoride
#+LANGUAGE: en
#+OPTIONS: ':nil *:t -:t ::t <:t \n:nil ^:t arch:headline author:t expand-links:t broken-links:mark c:nil creator:t d:(not "LOGBOOK") date:t e:t f:t H:3 inline:nil num:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t |:t toc:1
#+transclude: [[file:~/.config/emacs/table-lookup-settings.org]]

* Table of Contents :TOC_1:
- [[#whats-this-project][What's this project]]
- [[#how-to-run][How to run]]
- [[#data][Data]]
- [[#collecting-playlists][Collecting playlists]]
- [[#downloading-audio][Downloading Audio]]
- [[#executing-commands][Executing commands]]
- [[#everything-playlist][Everything playlist]]

* What's this project
It's a script that downloads my playlists and puts them into nice playlists (m3u files)
* How to run
To extract source code in emacs use the =org-babel-tangle= (=C-c C-v C-t=)

Then run the =the-playlist.bash= script
* Data
#+NAME: playlists-table
| name               | id                                 |
|--------------------+------------------------------------|
| balatro            | PLEITERw4PaKFs_uS0MoXkIfGbsYJHmWVU |
| silksong           | PLyfXx1BeqwFYFwnXDZo6xYSIsek2x2fhp |
| celeste            | PLyfXx1BeqwFbnI87AyqLP5XcEg1u5kydi |
| hollow_knight      | PLyfXx1BeqwFZXtJPE153jA-8NJWz579Pb |
| terraria           | PLyfXx1BeqwFb9eMbR78HzJtvhAuGH2rnc |
| calamity           | PLyfXx1BeqwFY7_xMkP9BCAogmUQbwFBjc |
| calamity_infernum  | PLyfXx1BeqwFb0IcIT2_cbShbguqGOvnaq |
| baba               | PLyfXx1BeqwFaO6xFIQXFhQTJtFdP4WYyc |
| deltarune          | PLyfXx1BeqwFakIcMEOb5L3hLLuTWHZhFv |
| undertale          | PLyfXx1BeqwFZoI5JKqSOCYTq9_fxIqPPc |
| isaac_rebirth      | PLyfXx1BeqwFYwjv_IHypwL_QeR4IT4rW_ |
| isaac_afterbirth   | PLyfXx1BeqwFYEsmSq2YcXYfPoSxhqUdKj |
| isaac_repentance   | PLyfXx1BeqwFYukH-L7NXfhom6UPaSb33N |
| isaac_antibirth    | PLyfXx1BeqwFZfbk9ksALFm-Q6hmQPacQ1 |
| minecraft          | PLyfXx1BeqwFZ3paVLhJwsHpuWM4zlhLPj |
| stardew_valley     | PLyfXx1BeqwFYtf2Dntv405dH8I9FP5GcV |
| cassette_beasts    | PLyfXx1BeqwFZw1-JcUkkxHcodnwr_W6Nd |
| RoA                | PLyfXx1BeqwFYNtQ2sBVUvZ0_PUYvGLe_x |
| rhythm_doctor      | PLyfXx1BeqwFYvPfUFBjkZvmpFYFbSJQ2R |
| luck_be_a_landlord | PLyfXx1BeqwFbcG-8eBmiIbmDtNmn4tq2H |
| anime              | PLyfXx1BeqwFZcwV_yqpe5khtlKWGf0jM_ |
| misc               | PLyfXx1BeqwFZzRwmxQ1To7HQN37pj1EAs |

#+NAME: op-table
| operation          | command                                                               |
|--------------------+-----------------------------------------------------------------------|
| naiive_download_pl | yt-dlp -t aac --restrict-filenames -o 'pool/%(title)s'                |
| download_pl_m3u    | yt-dlp --restrict-filenames -o '../pool/%(title)s.m4a' --get-filename |

* Collecting playlists
Queue up commands that download video titles and attatch the m4a file extension and put in an m3u file in the appropriate place
#+begin_src bash :var download_playlists_function=table-lookup(table=op-table,value="download_pl_m3u") :comments org :var playlists=playlists-table :tangle the-playlist.bash

  commands=()

  mkdir playlists

  for playlist_name in ${!playlists[@]}; do
      echo "[THE PLAYLIST] Added $playlist_name to queue"
      commands+=("($download_playlists_function ${playlists[$playlist_name]} > playlists/${playlist_name}.m3u && echo \"[THE PLAYLIST] Generated \\\"$playlist_name\\\" playlist\") &")
  done
#+end_src

* Downloading Audio
Queue up commands that download audio from playlists
#+begin_src bash :var download_audio_pl=table-lookup(table=op-table,value="naiive_download_pl") :comments org :tangle the-playlist.bash

  for playlist_name in ${!playlists[@]}; do
      echo "[THE PLAYLIST] Queued up $playlist_name playlist"
      commands+=("($download_audio_pl ${playlists[$playlist_name]} && echo \"[THE PLAYLIST] Finished Downloading $playlist_name\") &")
  done
#+end_src

* Executing commands
Up to this point we've built up a queue of commands. The commands get executed in a parallel way and in a way that when you press =C-c= (Ctrl-C) in the terminal, it exits propperly. This way also insures the terminal doesn't hang (pretty nifty eh?)
#+begin_src bash :comments org :tangle the-playlist.bash
  (trap 'kill 0' SIGINT; eval ${commands[*]} wait)
#+end_src
Yup that's it

* Everything playlist
Generates the *everything* playlist
#+begin_src bash :comments org :tangle the-playlist.bash
  rm -f playlists/everything.m3u
  cat playlists/* > playlists/everything.m3u
#+end_src

* TODO COMMENT Slowing down balatro tracks

I wanted to sequence this, however, I couldn't get this to work for whatever reason, it seemed to hang. It's only 5 tracks though, so it's not really a big issue.

Tracks are slowed down to 75% of of their original speed, just like in the game.
#+begin_src bash :tangle yes :tangle commands.bash :comments org
  handle_balatro () {
      mkdir -p "pool/tmp"
      cd "pool/tmp"
      echo "$1"
      yt-dlp -x --audio-quality 0 --audio-format opus --restrict-filenames -o '%(title)s' "${playlists[$1]}";
      balatro_list=($(ls))
      for track in ${balatro_list[@]}; do
  	  echo "track: ($track)"
  	  ffmpeg -y -i "$track" -strict -2 -filter:a "atempo=0.75" -vn "../$track"
      done

      cd "../.."
      rm "pool/tmp" -r
  }
#+end_src

* TODO COMMENT Goals [0/1]
  - [ ] Fix Balatro Playlist
  - [ ] Renaming specific vids according to id
  - [ ] Human Resource machine (when I finish it)
  - [ ] Fix the anime playlists (e.g. alternate ops, extended endings)
  - [ ] Drawn to life: The next chapter
